#spring.cloud.stream.bindings.output.contentType: application/json
#spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
#spring.cloud.stream.kafka.streams.binder.configuration:
#  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#
#spring.cloud.stream.bindings.policyPaid:
#  destination: policyPaid
#  producer:
#    headerMode: raw
#
#spring.cloud.stream.bindings.policyPaidIn:
#  destination: policyPaid
#  consumer:
#    headerMode: raw
#
#
#spring.cloud.stream.bindings.policyPaidAnalytic:
#  destination: policyPaidAnalytic
#  producer:
#    use-native-encoding: true
#
#    headerMode: raw
#
#spring.cloud.stream.bindings.policyPaidAnalyticIn:
#  destination: policyPaidAnalytic
#  group: panalytic
#  consumer:
#    use-native-encoding: true
#    headerMode: raw
#
#
## Materialized View
#
#spring:
#  cloud:
#    stream:
#      kafka:
#        streams:
#          bindings:
#            mbs.producer.value-serde: org.apache.kafka.common.serialization.Serdes$LongSerde
#            mbs.producer.key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#            mbs.consumer.value-serde: org.apache.kafka.common.serialization.Serdes$LongSerde
#            mbs.consumer.key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#
#
#spring.cloud.stream.bindings.policyPaidAnalyticIn.contentType: application/json
#
#
## policyAnalytic
##spring.cloud.stream.bindings.policyPaidAnalytic.binder: kafka
#spring:
#  cloud:
#    stream:
#      kafka:
#        streams:
#          bindings:
#            policyPaidAnalytic.producer.value-serde: org.apache.kafka.common.serialization.Serdes$LongSerde
#            policyPaidAnalytic.producer.key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#
#
## policyAnalyticIn
##spring.cloud.stream.bindings.policyPaidAnalyticIn.binder: kafka
#spring:
#  cloud:
#    stream:
#      kafka:
#        streams:
#          bindings:
#            policyPaidAnalyticIn.consumer.value-serde: org.apache.kafka.common.serialization.Serdes$LongSerde
#            policyPaidAnalyticIn.consumer.key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#
#
#
##For testing
#spring.cloud.stream.bindings.policyPaid.destination: policyPaid
#spring.cloud.stream.bindings.policyPaidAnalytic.destination: policyPaidAnalytic
##spring.cloud.stream.bindings.policyPaid.binder: kafka
#
